package online.zzzzzzz.mvc.tools.dao.entity;

import online.zzzzzzz.basics.entity.BaseEntity;

/**
 * @author zZZ....
 * @description 博客分类  实体类
 * @date 2022/3/8
 */
public class BlogTools extends BaseEntity {
    
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_tools.id
     *
     * @mbg.generated Wed Feb 01 03:13:48 UTC 2023
     */
    private Integer id;
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_tools.href
     *
     * @mbg.generated Wed Feb 01 03:13:48 UTC 2023
     */
    private String href;
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_tools.title
     *
     * @mbg.generated Wed Feb 01 03:13:48 UTC 2023
     */
    private String title;
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_tools.des
     *
     * @mbg.generated Wed Feb 01 03:13:48 UTC 2023
     */
    private String des;
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_tools.img
     *
     * @mbg.generated Wed Feb 01 03:13:48 UTC 2023
     */
    private String img;
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_tools.color
     *
     * @mbg.generated Wed Feb 01 03:13:48 UTC 2023
     */
    private String color;
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_tools.type
     *
     * @mbg.generated Wed Feb 01 03:13:48 UTC 2023
     */
    private String type;
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_tools.heap
     *
     * @mbg.generated Wed Feb 01 03:13:48 UTC 2023
     */
    private Integer heap =0;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blog_tools
     *
     * @mbg.generated Wed Feb 01 03:13:48 UTC 2023
     */
    private static final long serialVersionUID = 1L;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_tools.id
     *
     * @return the value of blog_tools.id
     *
     * @mbg.generated Wed Feb 01 03:13:48 UTC 2023
     */
    public Integer getId() {
        return id;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_tools.id
     *
     * @param id the value for blog_tools.id
     *
     * @mbg.generated Wed Feb 01 03:13:48 UTC 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_tools.href
     *
     * @return the value of blog_tools.href
     *
     * @mbg.generated Wed Feb 01 03:13:48 UTC 2023
     */
    public String getHref() {
        return href;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_tools.href
     *
     * @param href the value for blog_tools.href
     *
     * @mbg.generated Wed Feb 01 03:13:48 UTC 2023
     */
    public void setHref(String href) {
        this.href = href == null ? null : href.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_tools.title
     *
     * @return the value of blog_tools.title
     *
     * @mbg.generated Wed Feb 01 03:13:48 UTC 2023
     */
    public String getTitle() {
        return title;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_tools.title
     *
     * @param title the value for blog_tools.title
     *
     * @mbg.generated Wed Feb 01 03:13:48 UTC 2023
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_tools.des
     *
     * @return the value of blog_tools.des
     *
     * @mbg.generated Wed Feb 01 03:13:48 UTC 2023
     */
    public String getDes() {
        return des;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_tools.des
     *
     * @param des the value for blog_tools.des
     *
     * @mbg.generated Wed Feb 01 03:13:48 UTC 2023
     */
    public void setDes(String des) {
        this.des = des == null ? null : des.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_tools.img
     *
     * @return the value of blog_tools.img
     *
     * @mbg.generated Wed Feb 01 03:13:48 UTC 2023
     */
    public String getImg() {
        return img;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_tools.img
     *
     * @param img the value for blog_tools.img
     *
     * @mbg.generated Wed Feb 01 03:13:48 UTC 2023
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_tools.color
     *
     * @return the value of blog_tools.color
     *
     * @mbg.generated Wed Feb 01 03:13:48 UTC 2023
     */
    public String getColor() {
        return color;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_tools.color
     *
     * @param color the value for blog_tools.color
     *
     * @mbg.generated Wed Feb 01 03:13:48 UTC 2023
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_tools.type
     *
     * @return the value of blog_tools.type
     *
     * @mbg.generated Wed Feb 01 03:13:48 UTC 2023
     */
    public String getType() {
        return type;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_tools.type
     *
     * @param type the value for blog_tools.type
     *
     * @mbg.generated Wed Feb 01 03:13:48 UTC 2023
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_tools.heap
     *
     * @return the value of blog_tools.heap
     *
     * @mbg.generated Wed Feb 01 03:13:48 UTC 2023
     */
    public Integer getHeap() {
        return heap;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_tools.heap
     *
     * @param heap the value for blog_tools.heap
     *
     * @mbg.generated Wed Feb 01 03:13:48 UTC 2023
     */
    public void setHeap(Integer heap) {
        this.heap = heap;
    }
}